### ISSUE TITLE
Hide unknown numbers

### ISSUE THREAD

**Issue by abrain** [hopfenspace/corona.bayern#2]
Thanks for the project!

As seen in the snippet below, the numbers for cured and deaths are always set to zero. I think it might be better to not show these numbers at all, if they are not known? Currently, they provide a wrong impression.

https://github.com/hopfenspace/corona.bayern/blob/02dafb33f172ab6ebb753d527001caf28fcd3a18/preparedata.py#L46-L47

**Comment by M4GNV5** [comment]
You are right. Before switching to lgl.bayern.de we used a different source which had cured/death case information. We changed data sources in favour of official data over media reports based data.

**Comment by abrain** [comment]
Thanks 👍
