### ISSUE TITLE
Implement RKI data source

### ISSUE THREAD

**Issue by abrain** [hopfenspace/corona.bayern#3]
Data from RKI on administrative district level (including number of deaths) is now available at https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?outFields=*&where=1%3D1

You'd get the data for Bavaria with [this API call](https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?where=BL_ID%3D9&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&returnZ=false&returnM=false&returnExceededLimitFeatures=true&sqlFormat=none&f=pjson). `Content-Type` header still says `text/plain` although they return JSON 🤷🏻‍♂️

Unfortunately, I don't have the time to submit a PR at the moment.

**Comment by M4GNV5** [comment]
Alright, I've modified `preparedata.py` to work with the new source, however there are the following problems:
- i can't find any information about the update time of the data
- it seems to lag behind lgl.bayern.de
- it currently has a sum of 4892 while lgl.bayern.de shows 5.719

![](https://i.m4gnus.de/f39f2.png)

**Comment by abrain** [comment]
Nice! According to [this overview page](https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0) the data is updated once per day. The [RKI Dashboard](https://corona.rki.de/), which uses the datasource from above, specifies the time of the last update as "23.03.2020 00:00 Uhr". I think it's fair to assume, the data is updated around midnight.

P.S.: The parameter `f=pjson` in the query seems to return prettified JSON, which is roughly double the size compared to `f=json` which returns it unformatted.

**Comment by M4GNV5** [comment]
As of today the RKI datasource seems to be superior. It not only is more up to date than lgl.bayern.de they also added a `last_update` field.
I merged the RKI datasource into master, it is now live at https://corona.bayern
