### ISSUE TITLE
SSL-Certificate corona.bayern

### ISSUE THREAD

**Issue by SnejPro** [hopfenspace/corona.bayern#8]
There is an error with the ssl certificate at corona.bayern

![Screenshot_2022-01-19-09-42-39-73_d0ef7a9810af20f7b394f4f927b723b0.jpg](https://user-images.githubusercontent.com/11321022/150094906-7235cf38-b8b8-49a7-af45-62c9b00e3437.jpg)

**Comment by M4GNV5** [comment]
Hey thanks for the report. I remember fixing it after seeing this issue, but apparently forgot to close this issue.
